# RNA Secondary Structure (Dynamic Programming)

# Online visualization
http://rna.tbi.univie.ac.at/forna/

For example:

RNA Sequence: ACCGGUAGU

Secondary Structure: ((.....))

RNA Sequence: ACGUCGAUUCGAGCGAAUCGUAACGAUACGAGCAUAGCGGCUAGAC

Secondary Structure: .(.(((((((....)))))(((....))))(((.....).))))..

RNA Sequence: AUGGCCAUUGUAAUGGGCCGCUGA

Secondary Structure: (.((((((....)))).))..)..

# Online prediction
http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAfold.cgi
http://www.unafold.org/mfold/applications/rna-folding-form.php

For example:
RNA Sequence: ACGUCGAUUCGAGCGAAUCGUAACGAUACGAGCAUAGCGGCUAGAC


In [ ]:
import numpy as np

In [ ]:
# Define RNA sequence

#rna_seq = "AUGGCCAUUGUAAUGGGCCGCUGA"
rna_seq = 'ACGUCGAUUCGAGCGAAUCGUAACGAUACGAGCAUAGCGGCUAGAC'
# rna_seq = 'ACAUGAUGGCCAUGU'
# rna_seq = 'ACCGGUAGU'
# rna_seq = 'AAGACUUCGGAUCUGGCGACACCC'


In [ ]:
# Auxiliary function for printing the optimal values array
def print_contents(opt_val):
    for i in range(n-5-1, -1, -1):
        print(i, end=': ')
        for j in range(5, n):
            print(opt_val[i][j], end=' ')
        print()
    print('j:', end=' ')
    for j in range(5, n):
        print(j, end=' ')

In [ ]:
# Initializations
sequence = rna_seq
n = len(sequence)
opt_val = [[-1 for j in range(n)] for i in range(n)]
opt_val_pairs = [[[] for j in range(n)] for i in range(n)]

for i in range(n):
    for j in range(n):
        if i >= j-4:
            opt_val[i][j] = 0

A = np.array(opt_val)
print(A)
#print_contents(opt_val)

[[ 0  0  0 ... -1 -1 -1]
 [ 0  0  0 ... -1 -1 -1]
 [ 0  0  0 ... -1 -1 -1]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [ ]:
# A function for checking the validity of pairs. Valid combinations: {A, U} and {C, G}
setAU = set('A')
setAU.add('U')
setCG = set('C')
setCG.add('G')
valid_pairs = [setAU, setCG]

# η χρήση της δομής set εξυπηρετεί και τις δύο ακολουθίες AU και UA

# Check if two bases can be paired
# 'C', 'U' -> False
# 'G', 'C' -> True

print(valid_pairs)

[{'U', 'A'}, {'G', 'C'}]


In [ ]:
def can_pair(base_1:str, base_2:str)->bool:
  # Δώθηκε στο μάθημα
  # πρέπει να φτιάξω ένα σύνολο με τις εισόδους που μου έδωσε και να ελέγξω αν είναι valid
  pair = set(base_1)
  pair.add(base_2)
  return pair in valid_pairs

  # η δομή που έχω εγω είναι μία λίστα που κάθε στοιχείο της είναι ένα σύνολο

In [ ]:
# Dynamic Programming algorithm
# Returns the optimal value (int num of pairs)
# A secondary structure with the optimal number of pairs is stored in opt_val_pairs
# Reference: Algorithm Design, Kleinberg & Tardos, Section 6.5

"""
    opt_val[i][j] = get_opt_val(i, j-1)

    for t in range(.....):
      .......

    opt_val[i][j] = 1 + get_opt_val(i, t-1) +get_opt_val(t+1, j-1)
    opt_val[i][j] =max( get_opt_val(i, j-1), max(1 + get_opt_val(i, t-1) +get_opt_val(t+1, j-1)))
"""

    # δεν γνωρίζω το t, το οποίο παίρνει τιμές μέσα στην ακολουθία. Εξετάζω με ποια βάση μπορεί να συνδεθεί η τεελυταία βάση
    # για το παράδειγμα των 9 βάσεων το t μπορεί να πάρει τιμές [ i , j-5]
    # πρέπει να βρω ποιο είναι το ιδανικό. με δομή επάναληψης διατρέχω, βρίσκω την καλύτερη τιμή και αυτή περνάω ως τελική απάντηση
    # το κομμάτι αυτό είναι κάπως πολύπλοκο, θα πρέπει να το δούμε



'\n    opt_val[i][j] = get_opt_val(i, j-1)\n\n    for t in range(.....):\n      .......\n\n    opt_val[i][j] = 1 + get_opt_val(i, t-1) +get_opt_val(t+1, j-1)\n    opt_val[i][j] =max( get_opt_val(i, j-1), max(1 + get_opt_val(i, t-1) +get_opt_val(t+1, j-1)))\n'

In [ ]:
def get_opt_val(i:int, j:int)->int:

    if opt_val[i][j] == -1:
      if j - i <= 4:
        opt_val[i][j] = 0
      else:
        best = get_opt_val(i, j-1)
        best_pairs = opt_val_pairs[i][j-1]
        for t in range(i,j-4):
          if can_pair(sequence[t], sequence[j]):
            temp = 1 + get_opt_val(i, t-1) + get_opt_val(t+1, j-1)
            AddSet = [(t,j)] + opt_val_pairs[i][t-1] + opt_val_pairs[t+1][j - 1]
            if temp > best:
              best = temp
              best_pairs = AddSet
        opt_val[i][j] = best
        opt_val_pairs[i][j]= best_pairs

    return opt_val[i][j]

In [ ]:
# Compute the optimal solutions for each subsequence.
# The cells of the array opt_val will be filled in the order
# they are filled in the book, Figure 6.16
# Note: These calls not really needed.
# A single call: get_opt_val(0, n-1) would be sufficient.
"""
for k in range(5, n):
    for i in range(0, n-k):
        j = i + k
        get_opt_val(i, j)
        #print_contents(opt_val)
"""

'\nfor k in range(5, n):\n    for i in range(0, n-k):\n        j = i + k\n        get_opt_val(i, j)\n        #print_contents(opt_val)\n'

In [ ]:
print("Sequence: ", rna_seq)

get_opt_val(0, n-1)
# print(opt_val)
A = np.array(opt_val)
print(A)
print_contents(opt_val)
print()
print(f'{n=}')
optimal_value = opt_val[0][n-1]
print(f'{optimal_value=}')
print()
# print(opt_val_pairs[0][n-1])
sorted_pairs = sorted(opt_val_pairs[0][n-1])
sorted_pair_bases = [(sequence[i], sequence[j]) for i, j in sorted_pairs]

print(f'{sorted_pairs=}')
print(f'{sorted_pair_bases=}')

Sequence:  ACGUCGAUUCGAGCGAAUCGUAACGAUACGAGCAUAGCGGCUAGAC
[[ 0  0  0 ... 14 14 14]
 [ 0  0  0 ... -1 -1 -1]
 [ 0  0  0 ... -1 -1 -1]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
40: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 
39: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 
38: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 -1 -1 
37: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 -1 
36: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 -1 -1 -1 -1 
35: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 -1 -1 
34: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 -1 -1 -1 -1 
33: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 -1 -1 -1 
32: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
# Given the node pairs compute the secondary structure
# Example
# Input: n=9, sorted_pairs=[(0, 8), (1, 7)]
# Output: '((.....))'

def get_secondary_structure(n: int, sorted_pairs)->str:
  # Complete the code
  # Δώθηκε στο μάθημα

  # αρχικοποίηση string:
  s = '.'*n
  slist = list(s)

  for p in sorted_pairs:
    slist[p[0]] = "("
    slist[p[1]] = ")"

  # πρέπει να επαναφέρω την λίστα σε string, να το δω,
  final_string = "".join(slist)
  return final_string
# όσες βάσεις δεν συμμετέχουν σε ζευγάρι μπαίνει τελεία,
# η έξοδος που έχει δηλώνει ότι το ένα ζευγάρι ξεκινάει από το 0 στοιχείο και τελειώνει στο 8

# για κάθε ένα από τα διατεταγμένη ζεύγη στο πρώτο στοιχείο βάζω ( και στο δεύτερο το )

In [ ]:
secondary_structure = get_secondary_structure(n , sorted_pairs)
print(f'{secondary_structure}')

.(.(((((((....)))))(((....))))(((.....).))))..
